server:
  port: 8081

spring:
  application:
    name: GATEWAY-App

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/*]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
      - id: employee-app
        uri:  lb://EMPLOYEE-APP
        predicates:
        - Path=/employeeApp/**
        filters:
          - AuthenticationFilter
          - name: CircuitBreaker
            args:
              name: callEmployeeAppFallback
              fallbackUri: forward:/fallback/employeeApp
        
      - id: role-service
        uri:  lb://ROLE-SERVICE
        predicates:
        - Path=/role/**
        filters:
        - AuthenticationFilter
        
      - id: security-app
        uri:  lb://SECURITY-APP
        predicates:
        - Path=/securityApp/**
        filters:
        - name: CircuitBreaker
          args:
            name: callSecurityAppFallback
            fallbackUri: forward:/fallback/securityApp
        
eureka:
  client:
    service-url:
      defaultZode: http://localhost:8761/eureka
        

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway"